name: Build Test and Publish Nightly Packages

on:
  push:
    branches:
      - nightly

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        target: [<% for tgt in targets %>
          << tgt.name >>,<% endfor %>
        ]
        include:<% for tgt in targets %>
          - target: << tgt.name >>
            platform: << tgt.platform >>
            platform_version: << tgt.platform_version >><% endfor %>

    steps:
<% for tgt in targets %>
    - name: Build (${{ matrix.target }})
      uses: edgedb/edgedb-pkg/integration/containers/python/<< tgt.name >>@gha
      if: matrix.target == '<< tgt.name >>'
      env:
        SRC_REVISION: "${{ github.sha }}"
        PKG_REVISION: "<current-date>"
        PKG_SUBDIST: "nightly"
        PKG_PLATFORM: "${{ matrix.platform }}"
        PKG_PLATFORM_VERSION: "${{ matrix.platform_version }}"

    - name: Test (${{ matrix.target }})
      uses: edgedb/edgedb-pkg/integration/containers/test/<< tgt.name >>@gha
      if: matrix.target == '<< tgt.name >>'
      env:
        PKG_SUBDIST: "nightly"
        PKG_PLATFORM: "${{ matrix.platform }}"
        PKG_PLATFORM_VERSION: "${{ matrix.platform_version }}"
<% endfor %>

    - uses: actions/upload-artifact@v1
      with:
        name: builds-${{ matrix.target }}
        path: artifacts/${{ matrix.target }}

  publish:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        target: [<% for tgt in targets %>
          << tgt.name >>,<% endfor %>
        ]
        include:<% for tgt in targets %>
          - target: << tgt.name >>
            platform: << tgt.platform >>
            platform_version: << tgt.platform_version >><% endfor %>

    steps:
    - uses: actions/download-artifact@v1
      with:
        name: builds-${{ matrix.target }}
        path: artifacts/${{ matrix.target }}

    - name: Describe
      id: describe
      uses: edgedb/edgedb-pkg/integration/containers/describe/debian@gha
      env:
        PKG_SUBDIST: "nightly"
        PKG_PLATFORM: "${{ matrix.platform }}"
        PKG_PLATFORM_VERSION: "${{ matrix.platform_version }}"
<% for tgt in targets %>
    - name: Publish (${{ matrix.target }})
      uses: edgedb/edgedb-pkg/integration/containers/upload/<< tgt.family >>@gha
      if: matrix.target == '<< tgt.name >>'
      env:
        PKG_SUBDIST: "nightly"
        PKG_PLATFORM: "${{ matrix.platform }}"
        PKG_PLATFORM_VERSION: "${{ matrix.platform_version }}"
        PKG_VERSION_SLOT: "${{ steps.describe.outputs.edb-version-slot }}"
        PACKAGE_UPLOAD_SSH_KEY: "${{ secrets.PACKAGE_UPLOAD_SSH_KEY }}"

    - name: Test Published (${{ matrix.target }})
      uses: edgedb/edgedb-pkg/integration/containers/testpublished/<< tgt.name >>@gha
      if: matrix.target == '<< tgt.name >>'
      env:
        PKG_SUBDIST: "nightly"
        PKG_PLATFORM: "${{ matrix.platform }}"
        PKG_PLATFORM_VERSION: "${{ matrix.platform_version }}"
        PKG_VERSION_SLOT: "${{ steps.describe.outputs.edb-version-slot }}"
<% endfor %>

    - uses: actions/checkout@v1
      with:
        repository: edgedb/edgedb-docker
        ref: master
        path: edgedb/dockerfile

    - name: Publish Docker Image (${{ matrix.target }})
      uses: elgohr/Publish-Docker-Github-Action@2.6
      if: matrix.target == 'debian-stretch'
      with:
        name: edgedb/edgedb:nightly
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        snapshot: true
        dockerfile: dockerfile/Dockerfile
        workdir: dockerfile
        buildargs: version=${{ steps.describe.outputs.edb-version-slot }},subdist=.nightly
