name: Build Test and Publish Nightly Packages

on:
  push:
    branches:
      - nightly

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        target: [debian-stretch, centos-7]
        include:
          - target: debian-stretch
            platform: debian
            platform_version: stretch
          - target: centos-7
            platform: centos
            platform_version: 7

    steps:
    - name: Build (${{ matrix.target }})
      uses: edgedb/edgedb-pkg/integration/containers/python/debian-stretch@gha
      if: matrix.target == 'debian-stretch'
      env:
        SRC_REVISION: "${{ github.sha }}"
        PKG_REVISION: "<current-date>"
        PKG_SUBDIST: "nightly"
        PKG_PLATFORM: "${{ matrix.platform }}"
        PKG_PLATFORM_VERSION: "${{ matrix.platform_version }}"

    - name: Build (${{ matrix.target }})
      uses: edgedb/edgedb-pkg/integration/containers/python/centos-7@gha
      if: matrix.target == 'centos-7'
      env:
        SRC_REVISION: "${{ github.sha }}"
        PKG_REVISION: "<current-date>"
        PKG_SUBDIST: "nightly"
        PKG_PLATFORM: "${{ matrix.platform }}"
        PKG_PLATFORM_VERSION: "${{ matrix.platform_version }}"

    - name: Test (${{ matrix.target }})
      uses: edgedb/edgedb-pkg/integration/containers/test/debian-stretch@gha
      if: matrix.target == 'debian-stretch'
      env:
        PKG_SUBDIST: "nightly"
        PKG_PLATFORM: "${{ matrix.platform }}"
        PKG_PLATFORM_VERSION: "${{ matrix.platform_version }}"

    - name: Test (${{ matrix.target }})
      uses: edgedb/edgedb-pkg/integration/containers/test/centos-7@gha
      if: matrix.target == 'centos-7'
      env:
        PKG_SUBDIST: "nightly"
        PKG_PLATFORM: "${{ matrix.platform }}"
        PKG_PLATFORM_VERSION: "${{ matrix.platform_version }}"


    - uses: actions/upload-artifact@v1
      with:
        name: builds-${{ matrix.target }}
        path: artifacts/${{ matrix.target }}

  publish:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        target: [debian-stretch, centos-7]
        include:
          - target: debian-stretch
            platform: debian
            platform_version: stretch
          - target: centos-7
            platform: centos
            platform_version: 7

    steps:
    - uses: actions/download-artifact@v1
      with:
        name: builds-${{ matrix.target }}
        path: artifacts/${{ matrix.target }}

    - name: Publish (${{ matrix.target }})
      uses: edgedb/edgedb-pkg/integration/containers/upload/debian@gha
      if: matrix.target == 'debian-stretch'
      env:
        PKG_SUBDIST: "nightly"
        PKG_PLATFORM: "${{ matrix.platform }}"
        PKG_PLATFORM_VERSION: "${{ matrix.platform_version }}"
        PACKAGE_UPLOAD_SSH_KEY: "${{ secrets.PACKAGE_UPLOAD_SSH_KEY }}"

    - name: Publish (${{ matrix.target }})
      uses: edgedb/edgedb-pkg/integration/containers/upload/redhat@gha
      if: matrix.target == 'centos-7'
      env:
        PKG_SUBDIST: "nightly"
        PKG_PLATFORM: "${{ matrix.platform }}"
        PKG_PLATFORM_VERSION: "${{ matrix.platform_version }}"
        PACKAGE_UPLOAD_SSH_KEY: "${{ secrets.PACKAGE_UPLOAD_SSH_KEY }}"

    - name: Test Published (${{ matrix.target }})
      uses: edgedb/edgedb-pkg/integration/containers/testpublished/debian-stretch@gha
      if: matrix.target == 'debian-stretch'
      env:
        PKG_SUBDIST: "nightly"
        PKG_PLATFORM: "${{ matrix.platform }}"
        PKG_PLATFORM_VERSION: "${{ matrix.platform_version }}"

    - name: Test Published (${{ matrix.target }})
      uses: edgedb/edgedb-pkg/integration/containers/testpublished/centos-7@gha
      if: matrix.target == 'centos-7'
      env:
        PKG_SUBDIST: "nightly"
        PKG_PLATFORM: "${{ matrix.platform }}"
        PKG_PLATFORM_VERSION: "${{ matrix.platform_version }}"

    - uses: actions/checkout@v1
      with:
        repository: edgedb/edgedb-docker
        path: dockerfile

    # - name: Publish Docker Image (${{ matrix.target }})
    #   uses: elgohr/Publish-Docker-Github-Action@2.6
    #   with:
    #     name: edgedb/edgedb
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}
    #     snapshot: true
    #     dockerfile: dockerfile/Dockerfile
    #     workdir: dockerfile
    #     buildargs: version=${{ steps.testpublished.outputs.edb-version-slot }},subdist=.nightly
