name: Build Test and Publish Nightly Packages

on:
  push:
    branches:
      - nightly

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            platform: debian
            platform_version: stretch

    steps:
    - name: Build (${{ matrix.platform }} ${{ matrix.platform_vesion }})
      uses: edgedb/edgedb-pkg/integration/containers/python/debian-stretch@gha
      if: matrix.platform == 'debian' && matrix.platform_version == 'stretch'
      env:
        SRC_REVISION: "${{ github.sha }}"
        PKG_REVISION: "<current-date>"
        PKG_SUBDIST: "nightly"

    - name: Test
      uses: docker://debian:stretch
      if: matrix.platform == 'debian' && matrix.platform_version == 'stretch'
      with:
        entrypoint: .ci/test-package-debian.sh
