name: Build Test and Publish Nightly Packages

on:
  push:
    branches:
      - nightly

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest]

    steps:
    - name: Build (Debian Stretch)
      run: |
        echo "Foo"
