name: Build Test and Publish Nightly Packages

on:
  push:
    branches:
      - nightly

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest]

    steps:
    - name: Build (Debian Stretch)
      uses: edgedb/edgedb-pkg/integration/containers/python/debian-stretch@gha
      env:
        SRC_REVISION: ${{ github.sha }}
        PKG_REVISION: "<current-date>"
